CPP = g++
WINDRES = windres.exe
CPPFLAGS = -Wall -ansi -DTIXML_USE_STL -DALLEGRO_STATICLINK -I../include -I../tinyxml

all:
	$(CPP) $(CPPFLAGS) -c -o fraktale.o main.cpp
	$(WINDRES) -i fraktale_res.rc --input-format=rc -o fraktale_res.res -O coff 
